"""Export saved MCU v1 constants; never fits or selects model/thresholds."""
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def export():
    source = ROOT / 'outputs/mcu_v1_frozen/model_manifest.json'
    m = json.loads(source.read_text())
    assert m['features']['order'] == ['ga_C2', 'jerk_abs_mean', 'ga_parallel_peak']
    means, scales = m['scaler']['mean'], m['scaler']['scale']
    w = m['logistic']['coefficients']
    folded = [a / b for a, b in zip(w, scales)]
    bias = m['logistic']['intercept'] - sum(a*b for a,b in zip(folded,means))
    def arr(values):
        return '{' + ', '.join(format(x, '.17g') for x in values) + '}'
    def matrix(values):
        return '{' + ',\n    '.join(arr(row) for row in values) + '}'
    text = ['/* Generated by tools/export_model.py; no training. */',
            '/* manifest SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest() + ' */',
            '#ifndef FALL_MODEL_PARAMS_H', '#define FALL_MODEL_PARAMS_H', '#include "filters.h"',
            '/* Order: ga_C2, jerk_abs_mean, ga_parallel_peak. */']
    for name, values in [('FALL_SCALER_MEAN',means), ('FALL_SCALER_SCALE',scales),
                         ('FALL_WEIGHTS',w), ('FALL_FOLDED_WEIGHTS',folded)]:
        text.append(f'static const FallReal {name}[3] = {arr(values)};')
    for name, value in [('FALL_INTERCEPT',m['logistic']['intercept']),
                        ('FALL_FOLDED_INTERCEPT',bias), ('FALL_ALPHA',m['gravity']['alpha'])]:
        text.append(f'static const FallReal {name} = {value:.17g};')
    for name, key in [('BALANCED','balanced_reference'), ('SENSITIVITY','sensitivity_oriented_candidate')]:
        tau = m['documented_operating_points'][key]['score_threshold']
        text.extend([f'static const FallReal FALL_{name}_PROBABILITY = {tau:.17g};',
                     f'static const FallReal FALL_{name}_LOGIT = {math.log(tau/(1-tau)):.17g};'])
    text += ['static const FallReal FALL_SOS[2][6] = '+matrix(m['acceleration_filter']['sos'])+';',
             'static const FallReal FALL_ZI[2][2] = '+matrix(m['acceleration_filter']['unit_constant_input_zi_per_section'])+';',
             '#endif', '']
    (ROOT/'embedded/model_params.h').write_text('\n'.join(text), encoding='utf-8')
    return m

if __name__ == '__main__':
    export()
